# types/type_event.py
from enum import Enum

class TypeEvent(Enum):
    MUSIC_FESTIVAL = "MUSIC_FESTIVAL"
    ART_EXHIBITION = "ART_EXHIBITION"
    THEATER = "THEATER"
    FILM_FESTIVAL = "FILM_FESTIVAL"
    HANDICRAFT_FAIR = "HANDICRAFT_FAIR"
    DISCUSSION_CIRCLE = "DISCUSSION_CIRCLE"
    MUSEUM_EXHIBIT = "MUSEUM_EXHIBIT"
    FOLKLORE_EVENT = "FOLKLORE_EVENT"
    ONLINE_EVENT = "ONLINE_EVENT"
    IN_PERSON_EVENT = "IN_PERSON_EVENT"
