"""add unique constraint eventId+name to tiers

Revision ID: 8ddaca0ab4f3
Revises: 5742946cab4e
Create Date: 2025-06-05 09:38:51.603134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddaca0ab4f3'
down_revision: Union[str, None] = '5742946cab4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('tiers_name_key'), 'tiers', type_='unique')
    op.create_unique_constraint('uq_event_tier_name', 'tiers', ['eventId', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_tier_name', 'tiers', type_='unique')
    op.create_unique_constraint(op.f('tiers_name_key'), 'tiers', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('events', 'updatedAt')
    op.drop_column('events', 'createdAt')
    # ### end Alembic commands ###
