"""Initial Migrate

Revision ID: d526be82a788
Revises: 
Create Date: 2025-05-31 19:34:47.234483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd526be82a788'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('typeEvent', sa.Enum('FREE_EVENT', 'PAID_EVENT', 'ONLINE_EVENT', 'IN_PERSON_EVENT', 'MUSIC_FESTIVAL', 'ART_EXHIBITION', 'THEATER', 'FILM_FESTIVAL', 'HANDICRAFT_FAIR', 'DISCUSSION_CIRCLE', 'MUSEUM_EXHIBIT', 'FOLKLORE_EVENT', name='typeevent'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', 'VALID', 'CANCELLED', 'CLOSED', 'OPEN', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', 'VALID', 'CANCELLED', 'CLOSED', 'OPEN', name='status'), nullable=True),
    sa.Column('role', sa.Enum('USER', 'PRODUCER', 'SELLER', 'ADMIN', name='role'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('enterprise', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eventProducers',
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('producerId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ),
    sa.ForeignKeyConstraint(['producerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('eventId', 'producerId')
    )
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyerId', sa.UUID(), nullable=True),
    sa.Column('sellerId', sa.UUID(), nullable=True),
    sa.Column('purchaseDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'REFUNDED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=True),
    sa.Column('totalPrice', sa.Float(), nullable=False),
    sa.Column('paymentMethod', sa.Enum('CREDIT', 'DEBIT', 'PIX', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('eventId', sa.UUID(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', 'VALID', 'CANCELLED', 'CLOSED', 'OPEN', name='status'), nullable=True),
    sa.Column('eventId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchaseItems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchaseId', sa.UUID(), nullable=True),
    sa.Column('tierId', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Float(), nullable=False),
    sa.Column('totalPrice', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchaseId'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['tierId'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('purchaseId', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchaseId'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ownerId', sa.UUID(), nullable=True),
    sa.Column('tierId', sa.UUID(), nullable=True),
    sa.Column('sellerId', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', 'VALID', 'CANCELLED', 'CLOSED', 'OPEN', name='status'), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tierId'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('receipts')
    op.drop_table('purchaseItems')
    op.drop_table('tiers')
    op.drop_table('ratings')
    op.drop_table('purchases')
    op.drop_table('eventProducers')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
